functional:
  - Платформа должна предоставлять пользователям возможность регистрации и аутентификации (вход по Email, а также через сторонние сервисы GitHub и Discord).
  - Система должна поддерживать режим быстрой игры без регистрации ("Try simple battle").
  - Платформа должна обеспечивать соревновательный процесс между двумя игроками с синхронным отображением процесса написания кода соперника в реальном времени.
  - Платформа должна поддерживать различные уровни сложности.
  - Платформа должна поддерживать различные типы игры (с другим пользователем, с другом, с ботом).
  - Платформа должна поддерживать разное время контроля за игрой.
  - Платформа должна поддерживать различные задачи для игры.
  - Платформа должна поддерживать выполнение кода на различных языках программирования.
  - Платформа должна автоматически проверять решения и мгновенно определять победителя.
  - Платформа должна корректно отображать статистику игрока.
  - Запись турнира должна корректно отображаться, с возможностью остановиться или перейти к определенному временному интервалу.
non-functional:
  - Сайт должен быть адаптирован под мобильные устройства.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть совместим с последними версиями браузеров.
  - Сайт должен обрабатывать большое количество трафика.
  - Сайт должен быть доступен для пользователей без использования VPN (прямой доступ из сети Интернет).
implicit:
  - Разделы сайта должны быть интуитивно понятными.
  - При разрыве интернет-соединения пользователю должна отображаться информация об ошибке.
  - Система должна автоматически сохранять и обновлять историю матчей, набранные очки и статистику сезонов без необходимости ручного подтверждения со стороны игроков.
